### PR TITLE
Add address map for better client index looking up

### PR DESCRIPTION
**Pull request by kienhg96**

### CODE REVIEW

**Comment by gafferongames** [comment]
Some warnings need to be fixed, see above.

**Comment by gafferongames** [comment]
First issue. The map returns 0 if the client index isn't found, but client index of 0 is a valid index. 

Please change that to return -1 if client index is found

**Comment by gafferongames** [comment]
Please change

#define NETCODE_ADDRESS_MAP_BUCKETS 256

To be some function of the max clients, because as the max clients increases for the server, you will need more buckets.

**Comment by gafferongames** [comment]
Please add a unit test for the map

**Comment by kienhg96** [comment]
Ok, I'll check them

**Comment by kienhg96** [comment]
I fixed the issues above, please have a check

**Review by gafferongames — CHANGES_REQUESTED** [review]
Please add functions netcode_map_create and netcode_map_destroy that use the allocator, the same way these methods are used for other types. -- thanks!

**Comment by kienhg96** [comment]
I have added the create and destroy functions using allocator.
I think you should wrap the `allocator_context`, `allocate_function` and `free_function` to a new struct called `allocator`.
It could be much more convenient.

**Comment by gafferongames** [comment]
Merged. Thanks!

**Pull request merged**
